"""English for the dashboard's server-side display text, keyed by the Chinese.

catalog.py and settings.py keep their Chinese strings; their payloads add a
``*_en`` sibling looked up here. tests/unit/test_serve_labels_en.py fails when
a display string has no entry.
"""

from __future__ import annotations

EN: dict[str, str] = {
    "创建数据备份": "Create data backup",
    "把明确选择的数据集复制成可校验的湖快照，不请求数据源。": "Copy the selected datasets into a verifiable lake snapshot. Does not contact data sources.",
    "备份与恢复": "Backup and restore",
    "新备份名称": "New backup name",
    "备份存放目录（可选，绝对路径）": "Backup directory (optional, absolute path)",
    "备份数据集": "Datasets to back up",
    "还没有已发布的数据。": "No published data yet.",
    "校验数据备份": "Verify data backup",
    "重新计算备份文件摘要，检查缺失、损坏与清单一致性。": "Recompute backup file digests and check for missing or corrupt files and manifest mismatches.",
    "备份名称": "Backup name",
    "恢复数据备份": "Restore data backup",
    "校验后恢复到新的或空目录，完成后可检查恢复结果。": "Verify, then restore into a new or empty directory. You can inspect the result afterward.",
    "我确认恢复目标在当前数据湖之外，并了解仅恢复所选备份的内容。": "I confirm the restore target is outside the current data lake and understand only the selected backup's contents are restored.",
    "恢复目录（绝对路径）": "Restore directory (absolute path)",
    "跑一天的更新": "Run a day's update",
    "按配置顺序跑全部日更调度组，再跑事件流。某组失败也继续。": "Run every daily-update schedule group in config order, then the event streams. Continues if a group fails.",
    "日更": "Daily update",
    "交易日": "Trading day",
    "默认今天。": "Defaults to today.",
    "按补跑语义": "Run as catch-up",
    "补跑某一天，不走增量窗口。": "Re-run a specific day instead of the incremental window.",
    "不跑事件流": "Skip event streams",
    "研究包": "Research packs",
    "不选则跑全部调度组和事件流。选择后只跑对应调度组。": "Leave empty to run all schedule groups and event streams. If selected, only the matching schedule groups run.",
    "跑一个调度组": "Run a schedule group",
    "只跑选定的日更调度组。不写“今天已跑过”的标记，定时全流程仍会执行。": "Run only the selected daily-update schedule group. Does not mark today as done, so the scheduled full run still happens.",
    "调度组": "Schedule group",
    "这份配置没有日更调度组。": "This config has no daily-update schedule groups.",
    "补抓落后的数据集": "Catch up lagging datasets",
    "只重抓仍然落后于最后交易日的数据集。可限定调度组，或只重抓快照。": "Re-fetch only datasets still behind the last trading day. Optionally limit to schedule groups or to snapshots.",
    "补抓与恢复": "Catch-up and recovery",
    "只重抓快照": "Snapshots only",
    "限定调度组": "Limit to schedule groups",
    "不选就是全部已启用的组。": "Leave empty for all enabled groups.",
    "跑事件流": "Run event streams",
    "公告、监管事件和资讯。周末和节假日也会跑。": "Announcements, regulatory events and news. Also runs on weekends and holidays.",
    "这份配置没有事件流调度组。": "This config has no event-stream schedule groups.",
    "事件组": "Event groups",
    "不选就按配置顺序跑全部。": "Leave empty to run all in config order.",
    "自然日": "Calendar day",
    "默认今天，含周末与节假日。": "Defaults to today, including weekends and holidays.",
    "重试一次 run": "Retry a run",
    "重试指定 run 里失败的批次。初始化 run 会按初始化续跑。": "Retry the failed batches in a run. Initialization runs resume as initialization.",
    "重试失败的日更组": "Retry failed daily-update groups",
    "每个日更调度组最近一次失败的 run 各重试一次。": "Retry the latest failed run of each daily-update schedule group once.",
    "发布 staging": "Publish staging",
    "把这次 run 留在 staging 里、已经结束的数据发布到湖里。": "Publish the finished data this run left in staging to the lake.",
    "环境体检": "Environment health check",
    "离线检查配置、依赖和会悄悄坏掉的地方。不访问网络。": "Offline check of config, dependencies and silent failure points. No network access.",
    "初始化": "Initialize",
    "初始化数据湖": "Initialize data lake",
    "全市场标的。quick 是近 3 年，full 从各数据集的历史起点起，日线从 2016-01-01 起。": "All market instruments. quick covers the last 3 years; full starts from each dataset's history start, with daily bars from 2016-01-01.",
    "我知道初始化会按所选深度请求数据源，可能持续数小时。": "I understand initialization fetches from data sources at the selected depth and may take hours.",
    "深度": "Depth",
    "quick 为近 3 年；full 更深。": "quick is the last 3 years; full goes deeper.",
    "历史起点": "History start",
    "填写后覆盖上面的深度。": "Overrides the depth above when set.",
    "不改变初始化下载的内容。market 行情，fundamentals 基本面，universe 历史 ST。": "Does not change what initialization downloads. market: quotes, fundamentals: fundamentals, universe: historical ST.",
    "某阶段失败后继续": "Continue after a stage fails",
    "继续初始化": "Resume initialization",
    "续跑最近一次没跑完的初始化，已成功的批次会保留。": "Resume the latest unfinished initialization, keeping batches that succeeded.",
    "回填一个数据集": "Backfill a dataset",
    "先给出来源、范围和抓取方式，确认后才取数。": "Shows the source, range and fetch method first; fetching starts only after you confirm.",
    "定向补数": "Targeted backfill",
    "我确认按预览范围回填；不限标的或超过一年会大量请求数据源。": "I confirm the backfill for the previewed range. No instrument limit or more than a year means heavy data source requests.",
    "数据集": "Dataset",
    "没有可从面板回填的数据集。": "No datasets can be backfilled from the dashboard.",
    "起点": "Start",
    "终点": "End",
    "标的": "Instruments",
    "逗号分隔，如 600519.SH,000001.SZ。不填就是该数据集的默认范围。": "Comma-separated, e.g. 600519.SH,000001.SZ. Leave empty for the dataset's default range.",
    "重算派生数据": "Rebuild derived data",
    "从已发布的数据重算。全量会重写分区。15 / 30 / 60 分钟线默认不计算，选中后在这里入湖。": "Recompute from published data. Full mode rewrites partitions. 15 / 30 / 60-minute bars are skipped by default; select them to write them to the lake here.",
    "我确认全量重算并重写分区。": "I confirm a full rebuild that rewrites partitions.",
    "派生": "Derived",
    "全量重写": "Full rewrite",
    "新鲜度": "Freshness",
    "按数据集查看覆盖和新鲜度，只读。": "View coverage and freshness by dataset. Read-only.",
    "巡检": "Inspection",
    "校验覆盖": "Verify coverage",
    "只读校验湖的覆盖。退出码 1 表示有发现，不是命令出错。": "Read-only check of lake coverage. Exit code 1 means findings, not a command error.",
    "全湖审计": "Full lake audit",
    "跑一次全湖审计并写下快照。": "Run a full lake audit and save a snapshot.",
    "探测数据源": "Probe data sources",
    "复用 12 小时内的采集证据，只补探没碰过的来源。会请求第三方主机。": "Reuses collection evidence from the last 12 hours and probes only untouched sources. Contacts third-party hosts.",
    "出口标签": "Vantage label",
    "如 local、cn。不填用 local。": "e.g. local, cn. Defaults to local.",
    "重建度量表": "Rebuild metrics table",
    "重算行数、体积和来源分布。不取数。": "Recompute row counts, sizes and source distribution. No fetching.",
    "预览配置升级": "Preview config upgrade",
    "列出当前版本要补进配置的 step 和调度组，不写文件。": "List the steps and schedule groups this version would add to the config. Writes no files.",
    "我确认现在启动这一次操作。": "I confirm starting this operation now.",
    "这些开关会改之后的每一次取数，包括定时日更和收尾补抓。保存设置不会启动取数。标的列表、频率和交易所仍在配置文件里。": "These switches affect all future fetching, including scheduled daily updates and closing catch-up. Saving does not start fetching. Instrument lists, frequencies and exchanges stay in the config file.",
    "将写入当前配置，并先备份原文件。这次不会启动取数。": "Writes to the current config after backing up the original file. Does not start fetching.",
    "没有需要保存的改动。": "No changes to save.",
    "我确认保存这些设置。定时日更、收尾补抓和之后的命令都会按新值执行。": "I confirm saving these settings. Scheduled daily updates, closing catch-up and later commands will use the new values.",
    "本机环境变量 CNE_PUSH2_PAUSED 开着，关掉配置里的暂停无效，push2 仍然不会发出请求。": "The local environment variable CNE_PUSH2_PAUSED is on, so turning off the pause in config has no effect; push2 still sends no requests.",
    "数据源": "Data sources",
    "可选采集": "Optional collection",
    "日更覆盖": "Daily update coverage",
    "暂停 push2": "Pause push2",
    "停掉 push2、push2his 和 push2delay，请求不会发出。datacenter 和其他东财主机继续。这和下面的东财总闸是两个开关。": "Stops push2, push2his and push2delay; no requests are sent. datacenter and other EastMoney hosts continue. This is separate from the EastMoney master switch below.",
    "通达信": "TDX",
    "日线主源。关掉后日线不再向通达信取数。": "Primary daily bar source. When off, daily bars are no longer fetched from TDX.",
    "东财": "EastMoney",
    "公告、财务和资金流。关掉后不再请求东财。": "Announcements, financials and fund flows. When off, EastMoney is no longer requested.",
    "新浪日线": "Sina daily bars",
    "日线兜底。关掉后不再用新浪补日线。": "Daily bar fallback. When off, Sina is no longer used to fill daily bars.",
    "历史行情兜底。": "Historical quotes fallback.",
    "北交所官网": "BSE website",
    "当日北交所行情。它不是历史源。": "Same-day BSE quotes. Not a historical source.",
    "同花顺页面": "THS pages",
    "板块行情。关掉后不再请求同花顺公开页。": "Sector quotes. When off, THS public pages are no longer requested.",
    "巨潮": "CNINFO",
    "公告和监管。关掉后不再请求巨潮。": "Announcements and regulatory filings. When off, CNINFO is no longer requested.",
    "分钟线": "Minute bars",
    "默认关闭。打开后日更会按当前范围持续抓取。": "Off by default. When on, the daily update keeps fetching for the current scope.",
    "分笔": "Trade ticks",
    "期货与期权": "Futures and options",
    "默认关闭。打开后日更会抓取期货和期权。": "Off by default. When on, the daily update fetches futures and options.",
    "期货分钟线": "Futures minute bars",
    "默认关闭。打开后日更会抓取期货分钟线。": "Off by default. When on, the daily update fetches futures minute bars.",
    "日更覆盖的证券": "Securities in the daily update",
    "决定日更抓哪些证券。ST、停牌和已退市名称都会保留。": "Choose which securities the daily update fetches. ST, suspended and delisted names are kept.",
    "全部 A 股": "All A-shares",
    "不含北交所": "Excluding BSE",
    "全部代码（含 ETF/LOF）": "All codes (incl. ETF/LOF)",
    "同时抓取符合条件的 ETF 日线": "Also fetch eligible ETF daily bars",
    "额外抓取最近可回放、且交易所目录判定合格的 ETF 日线。默认关闭。": "Also fetch daily bars for ETFs that are recently replayable and qualify per the exchange directory. Off by default.",
    "开": "On",
    "关": "Off",
}


def en(text: str | None) -> str | None:
    """The English for *text*, or *text* itself when there is none."""
    if not text:
        return text
    return EN.get(text, text)
